### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by duarme** [Corsidia/Esmerise#60]
I prossimi passi da valutare:

- [x] Fatturazione elettronica Italia e EU
- [ ] Marketplace per i corsi white label
- [ ] Collegamento API per marketplace (Corsidia, uCV e simili)
- [ ] #150
- [ ] Possibilità di certificare i corsi tramite provider come Alteredu (dipende da #150)
- [ ] Supporto formato SCORM, ved: https://it.wikipedia.org/wiki/SCORM
- [ ] Landing Page per Aziende
